redhat-developer/kam

- pkg/cmd/ui/validate.go
- pkg/cmd/ui/validate_test.go
/kind bug
The error message presented to the user is wrong and must be fixed.
No
[ ] Updated
Fixes #1 
See details and screen shot in the issue
It's just a string change.  No impact on other function.
Test updated to expect the new string.
> [1] Fix incorrect error message

- docs/journey/day1/README.md
- pkg/pipelines/webhook/webhook.go
> Fix typo in error message for webhook

- docs/journey/day1/prerequisites/pipelines_operator.md
/kind bug
Fixes the link for the OpenShift Pipelines Operator image
Fixes #?
> Fix OpenShift Pipelines Operator image link

- Makefile
> /kind bug
> /kind design
> /kind flake
Fixes #?
> add --mod=readonly to ignore vendor

- docs/journey/day1/README.md
- docs/journey/day2/README.md
Documentation fix
This clarifies the use of the `--prefix` option, explaining how it changes the
output, and removes the `<prefix>` elements from all the paths.
Fixes: #32 
Fixes #?
> Clarify prefix in docs

- docs/commands/bootstrap/README.md
- docs/journey/day1/README.md
The docs should inform that the bootstrap process also supports interactive prompt. I have used `asciinema` to record the working of interactive prompt
[![asciicast](https://asciinema.org/a/P3hsAu34gvYrxp6DPsA3AgWyn.svg)](https://asciinema.org/a/P3hsAu34gvYrxp6DPsA3AgWyn)
Fixes #30 
> [Docs] Add a section about interactive prompt

- pkg/cmd/service/add.go
> Update default values for sealed secrets in service command

- scripts/openshiftci-presubmit-all-tests.sh
/enhancement
We need a script to be called by openshift-ci to invoke in order the kick off e2e tests.
See https://github.com/openshift/release/pull/12283
Fixes NA
pr https://github.com/openshift/release/pull/12283 should pass
> create dummy all tests script for openshift-ci 

- pkg/cmd/bootstrap.go
- pkg/cmd/bootstrap_test.go
- pkg/cmd/service/add.go
- pkg/pipelines/secrets/secrets.go
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Make use of constant default value for SS controller na/name to avoid future out of sync problem with these default values.
Fixes #?
> Make use of constant default value for SS controller na/name

- pkg/cmd/webhook/create.go
- pkg/cmd/webhook/list.go
- pkg/pipelines/config/utils_test.go
- pkg/pipelines/secrets/secrets_test.go
- pkg/pipelines/yaml/resources.go
….com/golang/go/wiki/CodeReviewComments#error-strings
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fix error message to remove capalization   according to https://github.com/golang/go/wiki/CodeReviewComments#error-strings
Fixes #?
> fix error message to remove capalization  

- docs/commands/README.md
- docs/journey/day1/README.md
- docs/journey/day1/prerequisites/argocd.md
- pkg/cmd/kam.go
> Fix typos in docs

- docs/commands/README.md
- pkg/cmd/kam.go
/kind bug
> /kind design
> /kind flake
https://github.com/redhat-developer/kam/pull/42
Fixes #?
> fix typos in docs and command

- OWNERS
/kind cleanup
Remove duplicate entry from root owners file
Fixes NA
see the OWNER file
> Remove duplicate entry from root owners file

- openshift-ci/build-root/Dockerfile
/kind cleanup
The test [container](https://github.com/redhat-developer/kam/blob/master/openshift-ci/build-root/Dockerfile) by default provides ```make```, ```gcc```, ```wget``` and ```git```. So further installation of same package is not required. 
Fixes NA
Prow job unit test should pass
> Test container cleanup

- README.md
> Organize the Getting Started

- .github/PULL_REQUEST_TEMPLATE.md
/kind cleanup
We need to make sure that prow should detect whatever the labels are available in the pr template.  
Fixes NA
Prow should detect these labels at the time of pr creation
```
/kind bug
/kind cleanup
/kind code-refactoring
```
NOTE: Later we can increase and sync the label category as per our need.  
EDIT: 
verified here at - https://github.com/redhat-developer/kam/pull/53#event-3832634205 and https://github.com/redhat-developer/kam/pull/53#event-3832634336
> Updating labels in pr template

- docs/journey/day1/README.md
- docs/journey/day2/README.md
Fixing some code snippets and typos for Day1 and Day2 journeys.
* [ x ] Documentation update is required by this PR.
* [ x ] Documentation has been updated.
https://issues.redhat.com/browse/GITOPS-362
Fixes #?
For the Tekton task fix, running the previous task will result in an error with v1beta1. The fix works with v1beta1.
> Doc PR for KAM Day1 and Day2

- docs/devconsole/README.md
Since the previous PR got merged, resolving a review comment in this PR 
Fixes #?
> Update devconsole docs

- docs/commands/kam_build.md
- docs/journey/day1/README.md
- docs/journey/day2/README.md
- pkg/cmd/bootstrap.go
- pkg/cmd/build.go
- pkg/cmd/service/add.go
- pkg/cmd/ui/ui.go
- pkg/pipelines/bootstrap.go
Adds some extra information about the "build" command and what it does.
Fixes #?
> Improve the command-line documentation for the build command.

- docs/journey/day1/README.md
- pkg/pipelines/bootstrap.go
- pkg/pipelines/bootstrap_test.go
- pkg/pipelines/git/repository_test.go
- pkg/pipelines/scm/repository.go
- pkg/pipelines/utils.go
- pkg/pipelines/utils_test.go
It triggers automatic creation of the Repository at the end of the bootstrap process.
```
$ kam bootstrap
Checking dependencies
✓  Checking if Sealed Secrets is installed with the default configuration [15ms]
✓  Checking if ArgoCD Operator is installed with the default configuration [30ms]
✓  Checking if OpenShift Pipelines Operator is installed with the default configuration [34ms]
Starting interactive prompt
? Provide the URL for your GitOps repository https://github.com/bigkevmcd/new-gitops.git
? Select type of image repository External Registry
? Image repository of the form <registry>/<username>/<repository> which is used to push newly built images. …
```
> Bootstrap git repo

- docs/commands/kam_bootstrap.md
- docs/journey/day1/README.md
- pkg/cmd/bootstrap.go
- pkg/cmd/bootstrap_test.go
- pkg/cmd/ui/ui.go
- pkg/pipelines/bootstrap.go
- pkg/pipelines/bootstrap_test.go
- pkg/pipelines/environment_test.go
- pkg/pipelines/secrets/secrets_test.go
- pkg/pipelines/utils.go
- pkg/pipelines/utils_test.go
- pkg/pipelines/yaml/resources_test.go
- test/error.go
/kind feature
Initialises and pushes the source to the previously created repository.
Fixes #?
https://issues.redhat.com/browse/GITOPS-377
> Push repo to GitHub

- pkg/pipelines/yaml/resources_test.go
/kind bug
When checking the ability to write to the filesystem, simplify the error
message checking to not rely on Linux OS.
Fixes #73 
> Fix issue with error message validation.

- scripts/openshiftci-presubmit-unittests.sh
github action validation and openshift CI validation should in sync. More details - https://github.com/redhat-developer/kam/pull/80#discussion_r521156535
Fixes NA
Openshift CI should validate mod status
> Add go mod status message in openshift CI

- openshift-ci/build-root/Dockerfile
Pre req for https://github.com/redhat-developer/kam/pull/85#issuecomment-731019172
Fixes issue found in https://github.com/redhat-developer/kam/pull/85#issuecomment-731019172
```sudo``` will be installed in the test [container](https://github.com/redhat-developer/kam/blob/master/openshift-ci/build-root/Dockerfile)
> Install sudo in test container

- docs/FAQ/GitopsFAQ.md
Adds a link to our instructions on configuring ArgoCD for access to multiple namespaces.
Fixes #?
> Add note about argocd permissions.

- docs/journey/day1/README.md
- docs/journey/day1/prerequisites/gitops_repo.md
> /kind bug
PR corrects the information provided in the docs
Yes
NA
Run `kam bootstrap` without creating a repo in github as suggested in documentation previously.
> Correct documentation w.r.t gitops repo creation.

- scripts/openshiftci-presubmit-all-tests.sh
Github token is needed for kam day 1 operation
Fixes part of https://issues.redhat.com/browse/GITOPS-333
Token should be exported in the test container
> Export GitHub token

- pkg/pipelines/utils.go
- pkg/pipelines/utils_test.go
/kind bug
Only add generated files to the git repository when bootstrapping.
Fixes #?
#96 
> Restrict adding files to just the generated ones.

- docs/commands/kam.md
- pkg/cmd/kam.go
/kind cleanup
Changes the long description of the kam comand from
```
"Kubernetes Application Manager (KAM) is a CLI tool to scaffold your GitOps repository"
```
to
```
"GitOps Application Manager (KAM) is a CLI tool to scaffold your GitOps repository"
```
Fixes #?
> Change long description

- docs/commands/kam_bootstrap.md
- go.mod
- pkg/cmd/bootstrap.go
/kind cleanup
Tweaks the command-line argument for saving keyring tokens to make it more in line with the other names.
Fixes #?
> Change the name of the keyring save command-line argument.

- docs/commands/kam_bootstrap.md
- pkg/cmd/bootstrap.go
Clarify the intent of the overwrite functionality.
Fixes #?
> Clarify that overwrite only overwrites the local filesystem.

- openshift-ci/build-root/Dockerfile
Fixing CI failure of my pr #87
Fixes NA
Pr #87 should pass
> Create ssh directory path

- docs/commands/kam_bootstrap.md
- docs/commands/kam_service.md
- docs/commands/kam_service_add.md
- pkg/cmd/bootstrap.go
- pkg/cmd/service/add.go
- pkg/pipelines/bootstrap.go
- pkg/pipelines/imagerepo/imagerepo.go
- pkg/pipelines/imagerepo/imagerepo_test.go
- pkg/pipelines/service.go
> /kind bug
Removes the Prompting for hostname for internal image registry. 
https://issues.redhat.com/browse/GITOPS-419
https://issues.redhat.com/browse/GITOPS-419
Run `kam bootstrap`
> fix: Prompting for hostname for internal image registry(GITOPS-419)

- scripts/setup-operators.sh
https://github.com/openshift/release/pull/14360#issuecomment-750816070
pr https://github.com/openshift/release/pull/14360 should pass
> Increase sealed-secrets installation timeout

- docs/journey/day1/README.md
Enhance the Day-1 experience with private repositories.
Otherwise the user will not understand why the private repo are not synced following the Day-1 instruction.
this is the docu update
#130 
This is only the docu change. In best case - imo - we will handle this in `kam bootstrap` logic
> Enhance docu, how to configure private git repos. Fix #130

- docs/commands/kam_service.md
- docs/commands/kam_service_add.md
- pkg/cmd/service/add.go
Indicates that service add does _not_ need an application source URL.
Indicate that a repo url is not needed.
Fixes #?
> Improve the documentation for the service-add command.

- pkg/pipelines/config/validate.go
- pkg/pipelines/config/validate_test.go
This adds a little extra detail when we detect a duplicate repo url.
Fixes #?
> Improve duplicate repo url error.

- docs/commands/kam.md
- docs/commands/kam_completion.md
- pkg/cmd/completion.go
- pkg/cmd/kam.go
Adds a shell completion command.
Fixes #145
> Add completion command.

- Dockerfile.serve
Can we build an image and serve `kam` from a container in OpenShift ?
> Add a dockerfile to create an image to serve kam binary

- README.md
A couple of brief notes on building the kam binaries.
Fixes #150 
> Add note on building

- docs/journey/day1/README.md
- pkg/pipelines/bootstrap.go
- pkg/pipelines/bootstrap_test.go
- pkg/pipelines/eventlisteners/routes.go
- pkg/pipelines/eventlisteners/routes_test.go
- pkg/pipelines/routes/routes.go
- pkg/pipelines/webhook/webhook.go
A new Route is created during bootstrapping to make the default generated Nginx container available for testing.
Fixes #?
> Create route for nginx

- docs/journey/day1/README.md
Now that the smart defaults changes have been merged: https://github.com/redhat-developer/kam/pull/158, we should update docs.
> [563] Smart defaults - update docs

- docs/journey/day1/README.md
- docs/journey/day2/README.md
Fixes some typos and punctuation in day1 and day2 docs. Also, minor rephrasing here and there and wording changes for sake of consistency.
No issue
N/A
> docs: Fix some typos, punctuation and phrasing

- docs/journey/day1/README.md
-Corrected grammar
-Added requirement for SSH keys connected to GitHub/GitLab and how to do that
Previously no mention of the need to have SSH key connected to GitHub/GitLab account to run `kam bootstrap` command
> Fix requirements section

- scripts/setup-operators.sh
/kind bug
kam bootstrap dependency check fails for sealed secret 
Fixes NA
kam bootstrap dependency check should not fail for sealed secret
> Fix sealed secret instance name typo

- scripts/prepare-test-cluster.sh
- scripts/setup-operators.sh
Installing OpenShift GitOps operator through test script
Fixes NA
> Install GitOps operator

- docs/journey/day1/README.md
/kind bug
https://github.com/redhat-developer/kam/issues/124#issuecomment-751435369
Fixes #124
Day1 journey Doc is updated
> Update bootstrap command in Day1 journey Doc

- test/e2e/features/basic.feature
Precise kam version check in the test feature file
Fixes N/A, directly saw it when I was checking the e2e test file
```make e2e``` test should pass in CI
> Precise version check

- Makefile
- docs/test/ci-guide.md
- docs/test/test-guide.md
- test/e2e/features/basic.feature
- test/e2e/features/manual.feature
- test/e2e/kamsuite/dirops.go
- test/e2e/kamsuite/kamsuite.go
On boarding doc for running and writing test for kam
Fixes #138
Please review and execute the steps mentioned in the .md file - https://github.com/redhat-developer/kam/pull/122/files#diff-8029d017233f39f36a19cc451bb8ad50f01a29944885d65b4d71b9459180db8c
> Onboarding test doc

- docs/journey/day1/prerequisites/quay.md
As per the screenshot in https://github.com/redhat-developer/kam/blob/master/docs/journey/day1/prerequisites/quay.md I am updating the doc
Fixes N/A
**How to test changes / Special notes to the reviewer**: 
The first prereq in https://github.com/redhat-developer/kam/blob/master/docs/journey/day1/prerequisites/quay.md should be in sync with the screenshot
> Updating quay prereq doc

- pkg/pipelines/service.go
- pkg/pipelines/service_test.go
> /kind bug
The `service add` command should generate trigger binding that injects the image repo into the trigger template. This commit adds default pipeline and image repo if they're absent.
Signed-off-by: Chetan Banavikalmutt <chetanrns1997@gmail.com>
Fixes https://issues.redhat.com/browse/GITOPS-755
1. Create a new env using the env add command
2. Create a new service in the newly added env
3. Add webhook to the new service repo
4. Make a PR to the new service repo and observe if the pipeline is successful
> fix: add defaults for image repo and pipelines

- .github/workflows/ci-build.yml
- go.sum
/kind failing-CI
Debugging purpose for https://github.com/redhat-developer/kam/pull/197/checks?check_run_id=2151513945#step:4:178
Fixes - Debugging purpose
Only for debugging purpose. No review is required.
> Git action CI failure debug

- test/e2e/features/local.feature
As we are putting all the local test scenario in the local.feature file, there is no need to define the local tag for each scenario. So I made the local tag feature level instead of scenario level
I was going through the kam test feature files and found this enhancement issue.
```make e2e-local```
> Make local tag global

- scripts/openshiftci-presubmit-all-tests.sh
- scripts/openshiftci-presubmit-unittests.sh
/kind cleanup
Remove unnecessary CI variables
Fixes #?
N/A
CI job should pass
> Remove unnecessary CI variables

- docs/journey/day1/README.md
As a noob to Kam, I ran into errors while running my First CI. I tried to create web-hook as suggested in the Day 1 operations and ran into the below error.
```
unable to create webhook: failed to get webhook secret: unable to get the secret &Secret{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Data:map[string][]byte{},Type:,StringData:map[string]string{},}: secrets "webhook-secret-dev-taxi" not found
```
I was able to fix this error by applying the secrets created by `kam bootstrap`. 
```oc apply -f secrets/
```
Yes
This is a doc update
> Update Day 1 operations for Sealed Secrets

- openshift-ci/build-root/Dockerfile.unprivileged
This change will not break our current CI. I need to merge this to provide more input to testplatform team on my issue https://github.com/redhat-developer/kam/issues/127.
Corresponding pr https://github.com/openshift/release/pull/18056 has been created to verify it.
> Unprivileged docker image

- openshift-ci/build-root/Dockerfile.temp
Fix https://github.com/redhat-developer/kam/pull/233 unit test job failure
> Temporary docker container1.16

- docs/journey/day1/README.md
https://github.com/redhat-developer/kam/pull/225#discussion_r629081838
Fixes - https://github.com/redhat-developer/kam/pull/225#discussion_r629081838
Review the day1 doc https://github.com/redhat-developer/kam/tree/master/docs/journey/day1#bringing-the-bootstrapped-environment-up
> Updating bootstrap environment up doc

- scripts/openshiftci-presubmit-all-tests.sh
- test/e2e/features/basic.feature
- test/e2e/kamsuite/kamsuite.go
https://github.com/redhat-developer/kam/issues/120
Fixes #120 
Test scenario should pass in CI
> Bringing the bootstrapped environment up

- scripts/setup-operators.sh
Fix of - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-developer_kam/237/pull-ci-redhat-developer-kam-master-v4.7-integration-e2e/1392449843313512448#1:build-log.txt%3A371
Fixes of https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-developer_kam/237/pull-ci-redhat-developer-kam-master-v4.7-integration-e2e/1392449843313512448#1:build-log.txt%3A371
> Update operator subscription channel

- scripts/setup-operators.sh
To fix CI failure - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-developer_kam/237/pull-ci-redhat-developer-kam-master-v4.7-integration-e2e/1395320374224228352#1:build-log.txt%3A354
Fixes - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-developer_kam/237/pull-ci-redhat-developer-kam-master-v4.7-integration-e2e/1395320374224228352#1:build-log.txt%3A354
Local and CI test suite kam bootstrap command should pass
> Install pipeline operator

- test/e2e/features/basic.feature
- test/e2e/kamsuite/kamsuite.go
> Bringing the deployment infrastructure up

- docs/journey/day1/README.md
- test/e2e/features/basic.feature
/kind bug
Fix wrong command
Fixes NA
```
$ oc apply -k config/argocd/ --dry-run=client
application.argoproj.io/argo-app configured (dry run)
application.argoproj.io/cicd-app configured (dry run)
application.argoproj.io/dev-app-taxi configured (dry run)
application.argoproj.io/dev-env configured (dry run)
application.argoproj.io/stage-env configured (dry run)
```
> Validate manifest yamls

- docs/journey/day1/README.md
Enhance initial doc.
Y
* [ x] Documentation has been updated.
None
Fixes #?
None
N/A
> Duplicate sentence, more useful one left.

- test/e2e/kamsuite/kamsuite.go
/kind bug
https://github.com/redhat-developer/kam/pull/256#issuecomment-872319847
Fixes - CI race condition
Both the 4.7 and 4.8 CI jobs should pass
> Fix CI repo delete race condition

- scripts/setup-operators.sh
/kind bug
Wrong string was passed to match pipeline csv - https://github.com/redhat-developer/kam/pull/256#pullrequestreview-700649349
Fixes - https://github.com/redhat-developer/kam/pull/256#pullrequestreview-700649349
```make prepare-test-cluster``` should not wait for 15 retries
> Update pipelines csv search string

- test/e2e/features/basic.feature
Fixes #?
`make e2e` should pass
> Scenarios for applying secrets and creating webhook

- OWNERS
- test/e2e/features/basic.feature
I am adding my name in the reviewer's list
Fixes #? N/A
> Updating owners file

- test/e2e/features/basic.feature
- test/e2e/kamsuite/dirops.go
- test/e2e/kamsuite/kamsuite.go
Added scenario for testing KAM bootstrap command with and without --overwrite flag. This pr also fixes the need to generate resource files with different names by kam bootstrap command (which are redundant) by cleaning up the directory before each scenario
Fixes #? N/A
```make e2e``` should pass
> Adding more scenarios for day1 operation

- test/e2e/features/basic.feature
- test/e2e/kamsuite/kamsuite.go
**Which issue(s) this PR fixes**: 
Fixes #?
https://github.com/redhat-developer/kam/issues/137
```make e2e``` should pass
> Scenario for adding webhook(day2)

- test/e2e/features/basic.feature
- test/e2e/kamsuite/kamsuite.go
Currently test suite contains time.Sleep() which is not the appropriate way for implementing wait. This pr replaces time.Sleep() with polling logic
Fixes #?
```make e2e``` should pass
> Replacing time.Sleep() with polling logic

- test/e2e/features/basic.feature
- test/e2e/kamsuite/kamsuite.go
Currently, login to ArgoCD API server is done for each scenario. In this pr we login to the API server before the test begins
Fixes #?
```make e2e``` should pass
> Login to ArgoCD API server before test suit

- scripts/prepare-test-cluster.sh
- scripts/setup-operators.sh
- test/e2e/features/basic.feature
- test/e2e/kamsuite/kamsuite.go
We do not have any e2e test scenarios to check if pipeline gets triggered when a PR is raised in source repository. This PR addresses the same
Fixes #?
> Adding webhook to the source repository

- docs/devconsole/README.md
- docs/devconsole/development.md
Dependent on merging of
PR1 -  https://github.com/redhat-developer/gitops-operator/pull/262
PR2 - https://gitlab.cee.redhat.com/gitops/operator-e2e/-/merge_requests/9
Fixes #?
Gitops-1668
> add route creation step for local development

- pkg/pipelines/bootstrap.go
- pkg/pipelines/service.go
- pkg/pipelines/service_test.go
Adds a config folder for newly created services using the service add command. The config folder will have a sample Nginx service manifests. 
Fixes #193 
Day 1 and Day 2 operations must succeed
> Add config folder for new services

- Makefile
> Adds support for ppc64le and s390x

- .gitignore
> /kind bug
/kind cleanup
Fixes #?
> add  .vscode to .gitignore
