.github/PULL_REQUEST_TEMPLATE.md

> /kind bug
/kind cleanup
> /kind design
> /kind flake
* Removed reference to the old doc site
* Add one more box to indicate if documentation update is required.   So, it will tell the reviewer that 1) if doc update is required 2) if doc has been updated.   (as two separate checkboxes)
See https://github.com/rhd-gitops-example/docs
[ ] Updated
Fixes #?
Not …

Improve documenation checkboxes in PR template

---

pkg/pipelines/bootstrap.go
pkg/pipelines/statustracker/deployment.go
pkg/pipelines/statustracker/deployment_test.go

Add a custom field and bump the image for commit-status-tracker to make it
easier to share secrets.
/kind bug
commit-status-tracker supports changing the name of the secret, which makes it nicer from our side.
Fixes #?

Support status-tracker secret sharing.

---

pkg/cmd/bootstrap.go
pkg/cmd/bootstrap_test.go
pkg/pipelines/helper/error.go
pkg/pipelines/yaml/resources.go
pkg/pipelines/yaml/resources_test.go

> /kind bug
* The interactive prompt can now accept relative path and tilde(`~`)
* Add .git suffix before checking dependencies
* Move the completion message to Run(), to keep the UX similar in both the modes
Fixes #?

Expand file path before writing resources

---

scripts/openshiftci-presubmit-unittests.sh

/kind feature
All platform bits should be available in prow artifacts directory for each pr
Fixes #38
Bits should be available here at - https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-developer_kam/39/pull-ci-redhat-developer-kam-master-unit/1310893860162899968/artifacts/unit/

Uploading kam bits to prow artifacts

---

go.mod
pkg/cmd/bootstrap.go
pkg/cmd/build.go
pkg/cmd/environment/add.go
pkg/cmd/environment/add_test.go
pkg/cmd/service/add_test.go
pkg/cmd/service/service.go
pkg/cmd/webhook/create.go
pkg/cmd/webhook/create_test.go
pkg/cmd/webhook/delete.go
pkg/cmd/webhook/delete_test.go
pkg/cmd/webhook/list.go
pkg/cmd/webhook/list_test.go
pkg/pipelines/argocd/argocd.go
pkg/pipelines/argocd/argocd_test.go

Removes all the removable references to `odo` from the source.
There are references to the sole import from odo in our source-tree.
Fixes #?

Strip remaining references to odo from the code.

---

pkg/cmd/bootstrap.go

> /kind bug
Git-host access token requires that the commit-status-tracker to be true, however on the UI side we get an error if the commit-status-tracker option is no. Hence the fix.

 The check for access token completed on the UI front

---

docs/journey/day2/README.md
pkg/pipelines/environment_test.go
pkg/pipelines/ioutils/file_utils.go
pkg/pipelines/service.go
pkg/pipelines/service_test.go

/kind bug
The `kam service add` command does not create the `config` folder in the base directory. This fix corrects that error.
https://issues.redhat.com/browse/GITOPS-360

kam service add creates a new config directory.

---

openshift-ci/build-root/Dockerfile

As per the doc https://github.com/redhat-developer/kam/blob/master/docs/journey/day1/prerequisites/gitops_repo.md we need to install the [github cli](https://github.com/cli/cli) in the test container to create a fresh github repo which will be used for Bootstrapping the Manifest input for each pr
Fixes NA
- Build the docker file https://github.com/redhat-developer/kam/compare/master...amitkrout:installingGithubCliInTestContainer?expand=1#diff-01f4ec918b634e024905add2f91a58ab
- Run it ```docker run -it <image_id>```
- In the container execute ```gh version```. It …

Installing github cli in test container

---

Makefile
docs/commands/kam_service.md
docs/commands/kam_service_add.md
scripts/openshiftci-presubmit-unittests.sh

Prow unable to sense github action failure. So to avoid merges after failure, i have added the `make docs` in the prow job so that the failure status will be identified and pr won't merge into the master. 
Fixes NA
`make docs` error should be reported in prow job

Fixing doc generate failure

---

Makefile

/kind cleanup
```openshiftci-presubmit-unittests.sh``` is written for CI operation, so we should not expose it in the make target as it gives a wrong message that this target can be run for local environment. So removing it.
Fixes https://github.com/redhat-developer/kam/pull/68#discussion_r509924498
CI should not fail.

Remove unnecessary make target

---

.github/workflows/release.yml
.gitignore
Makefile
scripts/openshiftci-presubmit-all-tests.sh
scripts/openshiftci-presubmit-unittests.sh

This PR changes the location of where binaries are outputted.   Instead of putting the built binaries (kam, etc) in the top level folder, they are not put in the "dist" folder.   .gitIngore file is updated to ignore files in "dist" folder.
Fixes #?
* Remove any `kam` binary at the top level folder.
* Run `make bin` to compile `kam`
* Check built file `ls -l dist`
* Run `make clean` 
* Check binaries are removed `ls -l dist`

output built binaries in  "dist" folder

---

scripts/install-argocd.sh
scripts/openshiftci-presubmit-all-tests.sh

This PR adds a script to install ArgoCD on darwin/linux that's needed as part of GITOPS-333 issue.
Documentation will be updated once the entire work is completed for GITOPS-333.
[GITOPS-333](https://issues.redhat.com/projects/GITOPS/issues/GITOPS-333) partial.
Execute this script on mac/linux where you don't have ArgoCD installed. The script will install ArgoCD CLI. Since the ArgoCD server address is not set, you might see an error at the end. But the goal of this script is to install ArgoCD CLI.

Adding argocd install script that can be referenced from other E2E tests

---

scripts/openshiftci-presubmit-all-tests.sh

Providing a developer login session to run the following operations 
kam CLI bootstraps and generates CI/CD pipelines with starter app, push to gitops repository, oc apply -f /config/argocd (i.e. create argocd apps in the generated config) etc...
Fixes NA
```
+ oc login -u developer -p developer
Login successful.
You have access to the following projects and can switch between them with 'oc project <projectname>':
* argocd
cicd
Using project "argocd".
+ oc whoami
developer
```
Check the prow log - https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci- …

Create developer login session in CI

---

scripts/install-argocd.sh
scripts/install-docker-cli.sh
scripts/openshiftci-presubmit-all-tests.sh

Adding Docker CLI install script that can be referenced from other E2E tests.
Partial of https://issues.redhat.com/browse/GITOPS-333
Fixes #?
N/A
Execute this script on your Mac or Linux machine. The script worked for me when I did not include the `bin/docker` part and used just `docker`. Added `bin/docker` to match the KAM CLI.

Adding Docker CLI install script 

---

README.md

Fix typo in commandline

---

docs/commands/kam_bootstrap.md
docs/commands/kam_webhook.md
docs/commands/kam_webhook_create.md
docs/commands/kam_webhook_delete.md
docs/commands/kam_webhook_list.md
docs/journey/day1/README.md
docs/journey/day2/README.md
go.mod
go.sum
pkg/cmd/bootstrap.go
pkg/cmd/bootstrap_test.go
pkg/cmd/ui/ui.go
pkg/cmd/ui/validate.go
pkg/cmd/webhook/create_test.go
pkg/cmd/webhook/delete_test.go
pkg/cmd/webhook/list_test.go
pkg/cmd/webhook/webhook_cmd.go
pkg/pipelines/accesstoken/accesstoken.go
pkg/pipelines/accesstoken/accesstoken_test.go
pkg/pipelines/bootstrap.go
pkg/pipelines/webhook/webhook.go
pkg/pipelines/webhook/webhook_test.go

This feature allows you to set the token at the time of bootstrap and can be reused at the time of the webhook create.
Will be addressed after Pr is approved.
https://issues.redhat.com/browse/GITOPS-349

Allow kam commands to reuse Git auth-token

---

pkg/pipelines/argocd/argocd.go
pkg/pipelines/argocd/argocd_test.go
pkg/pipelines/environments/environments.go
pkg/pipelines/environments/environments_test.go
pkg/pipelines/service_test.go

/kind cleanup
This breaks the link between apps and environments.
Previously, an app depended on its services, _and_ on its environment, this meant that you could bring up an app, and have it bring up the environment-defined resources.
This lead to issues, because an environment with multiple apps triggered a warning about multiple applications managing the same resource.
This change breaks this link, and introduces a per-env app, which is the recommended method for argo-cd.
Fixes #?
By default, this results in application being created by the argocd resource builder for each …

Break link app env

---

pkg/pipelines/argocd/argocd.go
pkg/pipelines/argocd/argocd_test.go

> /kind bug
Generated argocd application to use overlays folder instead of base. Given that we have an overlays directory, which is for users to override the base, we should be using the overlays directory, otherwise nothing that is put into the overlays will be picked up.
NA 
NA
Run `kam bootstrap` and see if the generated argocd application (/config/argcod/<env>-<app>-app,xml) spec/source/path uses "overlays" folder instead of "base".

Generated argocd application to use overlays folder instead of base

---

pkg/pipelines/pipelines/pipelines.go
pkg/pipelines/pipelines/pipelines_test.go
pkg/pipelines/triggers/pipelinerun.go
pkg/pipelines/triggers/pipelinerun_test.go
pkg/pipelines/triggers/templates.go
pkg/pipelines/triggers/templates_test.go

/kind bug
Fully supports the Buildah ClusterTask, by providing a workspace for cloning the code into and an image parameter for pushing the image to.
To do this, it introduces a Workspace to the App CI pipeline, and adds support for the git-clone task to checkout the code to the correct directory.
Fixes #?

Fix image param

---

pkg/pipelines/namespaces/namespaces.go
pkg/pipelines/namespaces/namespaces_test.go

We push the git repo to a "main" branch when it's being automatically created.
This generates the namespace with this default.
The vcs ref url is used by the Gitops backend to fetch the correct repo.
Fixes #?

Add default ref to namespaces.

---

pkg/pipelines/argocd/argocd.go
pkg/pipelines/argocd/argocd_test.go
pkg/pipelines/bootstrap_test.go
pkg/pipelines/environments/environments.go
pkg/pipelines/environments/environments_test.go
pkg/pipelines/resources/kustomization.go
pkg/pipelines/service_test.go

It adds two labels to objects that are created
"app.openshift.io/vcs-source" to all objects that are created, with a value that is the "fullname" of the GitOps Repo.
"app.kubernetes.io/name" is added to all ArgoCD Application objects, with the source application that they come from.
Fixes #?

Add app labels to applications

---

pkg/cmd/ui/ui.go

/kind bug
See https://github.com/redhat-developer/kam/issues/151
Fix case consistency: yes/no from Yes/No.  Most prompts currently are lower case
Fixes https://github.com/redhat-developer/kam/issues/151

Inconsistent case in Yes/No (yes/no) type of options in bootstrap cmd

---

pkg/cmd/bootstrap.go
pkg/cmd/bootstrap_test.go

In the bootstrap use case does the checkDependency logic does not take into account if the user provide custom values for SealedSecrets (service-name, namespace). This results in wrong info in the spinner and let the impression that something is wrong during bootstrap.
This enhancement is necessary, because the SealedSecrets Operator in OpenShift is installed in other namespace (not `cicd`)
No docu update necessary
n/a
Fixes #?
* Test boostrap with the parameters `--sealed-secrets-ns` and `--sealed-secrets-svc`
```
dist/kam_darwin_amd64 bootstrap \ …
```

Improve sealedsecret namespace

---

pkg/pipelines/service.go
pkg/pipelines/service_test.go

> /kind bug
Don't fail when you provide a service with an image to an environment with no pipelines
Fixes #?
#102 

Don't fail when adding a service to an environment with no pipelines.

---

docs/commands/kam_bootstrap.md
pkg/cmd/bootstrap.go
pkg/cmd/bootstrap_test.go
pkg/cmd/ui/ui.go
pkg/cmd/ui/validate.go
pkg/pipelines/bootstrap.go

Have to create another PR. I had an issue with rebase with the original PR: https://github.com/redhat-developer/kam/pull/148.
It's easier just to create a new PR and close the other one.
Use this one instead, but see comments from the original PR.
This is for the smart defaulting for kam bootstrap. This also includes a bug fix for #147 , since testing of the feature uncovered the bug.
/kind bug - Fixes 147
/kind enhancement - See GitOps story 563.  Fixes points 1 to 4.
See
GitOps story 563 points 1-4
#147
(Not yet)
Fixes #147
and GitOps story 563 points 1-4
**How to test changes / …

Smart default for bootstrap options except for epic point 5; Fix 147

---

pkg/cmd/ui/ui.go

/kind bug
Bad user experience if user inadvertantly adds leading and trailinig spaces to certain inputs.
Kam exits with error.
No doc update required.
Fixes #142 
I tested this by adding leading and trailing spaces to all applicable prompts, except for secrets and the git access token

[142] kam should trim leading and trailing spaces from input

---

pkg/pipelines/triggers/pipelinerun.go
pkg/pipelines/triggers/pipelinerun_test.go

/kind bug
There was a change to TriggerTemplate parameter naming, which involved adding a 'tt.' prefix.
This ensures that the TriggerTemplates that are generated will have the correct prefix.
See the breaking change here https://github.com/tektoncd/triggers/releases/tag/v0.7.0
(OpenShift pipelines has been updated to use v0.8.x)
Fixes #?

Switch to the new TriggerTemplate param naming.

---

pkg/pipelines/git/repository.go
pkg/pipelines/git/repository_test.go

/kind bug
This fixes the behaviour when parsing GitLab's "project" repos, where a repo
can be inside a project.
The change is to assume that everything after the host is part of the repo,
thus https://gitlab.com/org/project/repo.git would be from repo
org/project/repo.
Fixes: #166 
Create a group, create a new repo in the group (cloning from an existing one that you're using).
Use the full repo URL in the service repo url e.g. https://gitlab.com/group/subgroup/repo.git
**There's a caveat around this, it doesn't currently support automatically creating a new repo within a group** …

Improve support for GitLab project repos.

---

pkg/pipelines/bootstrap_test.go
pkg/pipelines/imagerepo/imagerepo.go

/kind bug
When the internal registry is used, we generate more than one namespace file.
This causes issues in ArgoCD because there are duplicates of the same K8s object.
This ensures that the files have the same name, which means that whichever way they are created, they exist in the directory.
Fixes #?

Address issue with multiple namespace files being created.

---

pkg/pipelines/bootstrap.go
pkg/pipelines/resources/kustomization.go
pkg/pipelines/resources/kustomization_test.go

This adds functionality for adding resources to the Kustomization, which will
filter out duplicate entries and maintain the element in string-sorted order.
Fixes #?

Remove duplicates when adding to the Kustomization representation.

---

docs/journey/day1/README.md
docs/journey/day1/prerequisites/argocd.md
docs/journey/day1/prerequisites/gitops_operator.md
pkg/cmd/bootstrap.go
pkg/cmd/bootstrap_test.go
pkg/pipelines/argocd/argocd.go
pkg/pipelines/bootstrap.go
pkg/pipelines/bootstrap_test.go
pkg/pipelines/environments/environments.go
pkg/pipelines/environments/environments_test.go
pkg/pipelines/roles/service_rolebinding.go
pkg/pipelines/service_test.go

The Kam CLI should generate role bindings for each environment that makes argocd an admin in that environment. The rolebinding file `argocd-admin.yaml` will be generated during bootstrap and while adding environments
```shell
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
creationTimestamp: null
name: argocd-admin
namespace: prod
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: ClusterRole
name: admin
subjects:
- kind: ServiceAccount
name: argocd-cluster-argocd-application-controller
namespace: openshift-gitops
```
It also generates a cluster role that aggregates sealed secrets to the OpenShift admin cluster role. This should be removed once it's fixed in upstream sealed …

Make Argo CD admin in environments managed by kam

---

openshift-ci/build-root/Dockerfile
scripts/openshiftci-presubmit-all-tests.sh
scripts/openshiftci-presubmit-unittests.sh
scripts/prepare-test-cluster.sh
test/e2e/features/basic.feature
test/e2e/kamsuite/kamsuite.go

Adding e2e test coverage for kam bootstrap command
Fixes #119
```make e2e``` test target should pass in CI
Test locally:
1. Login to the cluster as kubeadmin
2. The files ```kubeadmin-password``` and ```kubeconfig``` which contain cluster login details should be present in the auth directory and it should reside in the same directory as Makefile
2. Run ```make prepare-test-cluster```
3. Export these variables 
```
export SERVICE_REPO_URL=https://github.com/<your_github_org_name>/taxi
export GITOPS_REPO_URL=https://github.com/<your_github_org_name>/gitops.git …
```

Executing kam bootstrap command

---

pkg/cmd/bootstrap.go
pkg/cmd/ui/ui.go
pkg/cmd/ui/validate.go
pkg/cmd/ui/validate_test.go

> /kind bug
This PR fixes the validation and error handling for invalid GitOps Repo and service repo URLs
Fixes #?
ISSUE:
```
kam bootstrap
Checking dependencies
✓  Checking if Sealed Secrets is installed with the default configuration [941ms]
✓  Checking if ArgoCD is installed with the default configuration [2s]  
✓  Checking if OpenShift Pipelines Operator is installed with the default configuration [2s]
Starting interactive prompt
? Do you want to accept all default values and be prompted only for the minimum required options? no
? Provide the URL for your GitOps repository …
```

fixed panic for invalid gitops/service repo URL

---

docs/commands/kam_bootstrap.md
docs/commands/kam_service.md
docs/commands/kam_service_add.md
docs/journey/day1/README.md
docs/journey/day2/README.md
pkg/cmd/bootstrap.go
pkg/cmd/bootstrap_test.go
pkg/cmd/service/add.go
pkg/cmd/ui/ui.go
pkg/cmd/utility/utility.go
pkg/pipelines/bootstrap.go
pkg/pipelines/bootstrap_test.go
pkg/pipelines/secrets/secrets.go
pkg/pipelines/service.go
pkg/pipelines/service_test.go

For those cases where customers did not install the Sealed Secrets Operator, we need KAM to still work without generating sealed secrets.  We will generate the unencrypted/unsealed secrets which can be secured separately.
See https://issues.redhat.com/browse/GITOPS-677
Kevin wanted a new flag `--insecure` flag to give users the capability to force using unencrypted secrets and not by simply failing on the check that the sealed secrets operator is not installed.

KAM to function without security manager

---

pkg/pipelines/scm/github.go
pkg/pipelines/scm/github_test.go
pkg/pipelines/scm/gitlab.go
pkg/pipelines/scm/gitlab_test.go

> /kind bug
The Overlays in the Tekton event listener will add elements to a new field known as "extensions" instead of modifying the existing fields in the incoming payload.
This PR updates the trigger binding to extract the branch name from the new extensions field.
Overlays Ref: https://github.com/tektoncd/triggers/blob/v0.10.2/docs/eventlisteners.md#overlays 
Signed-off-by: Chetan Banavikalmutt <chetanrns1997@gmail.com>
1. Follow Day 1 docs and bootstrap a gitops repository
2. Add webhooks to gitops and service repository
3. Raise PRs to your gitops and service repositories, observe if both the pipelines are …

fix: Update trigger binding to use the new extensions field

---

Makefile
docs/test/test-guide.md
test/e2e/features/local.feature
test/e2e/kamsuite/kamsuite.go

Due to certain technical challenges in OpenShiftCI test infra. we are keeping test scenario in local feature file for verifying the bits locally. Once the CI challenges are fixed, we move these test under basic tags for CI run.
Fixes - As per @chetan-rns request i created it.
```
$ export SERVICE_REPO_URL=<Provide the URL for your Service repository>
$ export GITOPS_REPO_URL=<Provide the URL for your GitOps repository>
$ export IMAGE_REPO=<Image repository which is used to push newly built images>
$ export DOCKERCONFIGJSON_PATH=<Filepath to config.json which …
```

Template for running specific local tests

---

scripts/openshiftci-presubmit-unittests.sh

/kind cleanup
Vendor is part of kam repo. So no need to call it again in OpenShift CI
Fixes #?
N/A
CI should pass

Remove unnecessary call from OpenShift CI unit test job

---

scripts/openshiftci-presubmit-all-tests.sh

/kind cleanup
Vendor is part of kam repo. So no need to call it again in OpenShift CI
Fixes #?
N/A
CI should pass

Remove unnecessary call from OpenShift CI e2e test job

---

docs/commands/kam_bootstrap.md
pkg/cmd/bootstrap.go

Signed-off-by: iam-veeramalla <abhishek.veeramalla@gmail.com>
Commit status tracker is an experiential project hosted in Tekton.  Tekton will support this feature out of the box in future release.   The current status of commit status tracker is not stable as it has not been kept up-to-date with Tekton APIs changes.   We should hide user visible option to enable commit status tracker for the time being until we switch over to use the native support in Tekton (ref to ticket).
Fixes #?
https://issues.redhat.com/browse/GITOPS-750
Follow Day 1 operations to create a new gitops repo and webhook to trigger pipelines. After this change, you should not see the commit status …

Disable --commit-status-tracker by default

---

docs/journey/day1/README.md
pkg/pipelines/argocd/argocd.go
scripts/setup-operators.sh

/kind code-refactoring
The default Argo CD instance name would be changed to **openshift-gitops**  when the https://github.com/redhat-developer/gitops-operator/pull/70 is merged. The associated change has been made in KAM
https://issues.redhat.com/projects/GITOPS/issues/GITOPS-776 
Fixes #?
Perform the Day 1 operations. All the app should be synced in Argo CD.

Rename OpenShift GitOps default Argo CD instance name in KAM

---

pkg/pipelines/namespaces/namespaces.go
pkg/pipelines/namespaces/namespaces_test.go

Once the backend [PR](https://github.com/redhat-developer/gitops-backend/pull/16) to update the default ref goes in, we should update the ref generated by kam 

Update default ref in the annotation URL

---

scripts/install-kubectl.sh
scripts/openshiftci-presubmit-all-tests.sh

To get the argocd admin password we need the kubectl command to execute command ```$ kubectl get secret argocd-cluster-cluster -n openshift-gitops -ojsonpath='{.data.admin\.password}' | base64 -d```. So we need the kubectl binary available in openshift CI test container path.
Fixes #?
N/A
In the CI test container kubectl binary should be downloaded to ```bin/``` directory. For local verification you can execute the script ```install-kubectl.sh```  and check the kubectl binary should be downloaded to ```bin/``` directory

Adding kubectl binary in openshift CI test container

---

docs/commands/kam_service.md
docs/commands/kam_service_add.md
pkg/cmd/service/add.go

/kind bug
Misleading information
https://issues.redhat.com/browse/GITOPS-829
Run: kam service -h and look at the description of the --git-repo-url flag
Currently, it says:
GitOps repository e.g. https://github.com/organisation/repository - only needed when you need to rebuild the source image for the environment

The description for the kam service --git-repo-url option is wrong (829)

---

scripts/install-argocd.sh

Locks argocd cli version to v1.8.7
Fixes - https://github.com/redhat-developer/kam/pull/214#discussion_r604603949
```
$ PLATFORM=`uname -s | awk '{print tolower($0)}'`
$ curl -sSL -o bin/argocd https://github.com/argoproj/argo-cd/releases/download/v1.8.7/argocd-$PLATFORM-amd64
$ chmod +x bin/argocd 
$ bin/argocd version
argocd: v1.8.7+eb3d1fb
BuildDate: 2021-03-03T07:14:50Z
GitCommit: eb3d1fb84b9b77cdffd70b14c4f949f1c64a9416
[...]
```

Locking argocd cli version

---

pkg/pipelines/utils.go

/kind bug
This PR fixes the error message that is returned when `push-to-git` is enabled and the repo already exists. Earlier the error message was not informative for the user to understand the reason for failure. 
Fixes #?
Try to bootstrap a git repo that already exists. 
It should return an error message saying "repo[repo name] already exists" as the reason for failure.
PS: tried adding test cases for this, but it uses a mock provided by a vendor package and it doesn't throw an error on `CREATE repo`, if it already exists, simply overrides it.

fixed the error message for push-to-git if repo exists

---

pkg/cmd/bootstrap.go
pkg/cmd/ui/ui.go

We wanted to force users to specify --insecure from the command line because it is not a recommend option.  But for consistency, we should add it in interactive mode.  The message should be carefully worded to indicate it is not recommended.
Make --insecure option available in interactive mode
https://issues.redhat.com/browse/GITOPS-812
See https://issues.redhat.com/browse/GITOPS-812 for scenarios and interactive mode examples.

Insecure option is not available in interactive mode (812)

---

pkg/pipelines/argocd/argocd.go

/kind bug
Apps fail to sync in ArgoCD because of the ArgoCD instance name change, when a kam bootstrapped configuration is used.
Fixes #?
No bug opened
I've tested the three file changes manually against a cluster.  Tested kam bootstrap afterward to ensure the same changes are made to those three files. Ran `make test` successfully.

Update ArgoCD Service Account name

---

pkg/cmd/bootstrap.go
pkg/cmd/ui/ui.go
pkg/pipelines/bootstrap.go
pkg/pipelines/bootstrap_test.go
pkg/pipelines/utils.go
pkg/pipelines/utils_test.go

Resolves issue https://github.com/redhat-developer/kam/issues/212
/kind bug
**Why we need it**:
The bootstrap command  
```
kam bootstrap --service-repo-url https://github.com/ishitasequeira/taxi --gitops-repo-url https://github.com/ishitasequeira/gitops.git --image-repo quay.io/isequeir/taxi --dockercfgjson isequeir-robot-auth.json --git-host-access-token ******* --output resources --overwrite --push-to-git=true
``` 
when applied to the existing output directory, the folder gets updated but the remote origin does not get updated according to the new repo and the bootstrap command fails with below error.
**What does this PR do**:
In this PR, we fix the above issue. While executing the bootstrap command, we check if the overwrite flag is set  or not set, …

bug: delete existing .git directory if push-to-git and overwrite are set

---

pkg/cmd/bootstrap.go
pkg/cmd/bootstrap_test.go

> /kind bug
Fixes #?
1. Warning message for pipelines operator not found should ask users to install the Pipelines operator from OperatorHub

Fix warning message when pipelines operator is not found

---

pkg/cmd/bootstrap.go
pkg/cmd/ui/validate.go
pkg/cmd/ui/validate_test.go

/kind bug
The error message is saying that the token provided is not correct, even though it is.  The issue is that the token validation failed because the git driver was not provided for an private git repo (eg --private-repo-driver=gitlab).  This only happens in non-interactive mode from the command line.  In interactive mode, if the user is prompted for this value, so it's not a problem there.  The error message is changed to indicate that the token validation failed, instead of incorrectly saying that the token is wrong.  Also, the error message should suggest the correct course of action (to specify the aforementioned flag).  
The necessity to add this flag when an …

Improve error message if the git driver flag is not specified (#987)

---

pkg/pipelines/eventlisteners/routes.go
pkg/pipelines/eventlisteners/routes_test.go
pkg/pipelines/routes/routes.go
pkg/pipelines/routes/routes_test.go

Routes generated by Kam should use service port names instead of hardcoded numbers
**Which issue(s) this PR fixes**: #243 
Fixes #?
1. The route generated for event listener and sample service should refer to port name
2. Day 1 operations should work as expected

Use port name instead of number

---

pkg/pipelines/argocd/argocd.go
pkg/pipelines/argocd/argocd_test.go
pkg/pipelines/bootstrap.go
pkg/pipelines/config/config_test.go
pkg/pipelines/config/parser.go
pkg/pipelines/config/validate.go
pkg/pipelines/dryrun/dryrun_test.go
pkg/pipelines/environment_test.go
pkg/pipelines/environments/environments.go
pkg/pipelines/imagerepo/imagerepo.go
pkg/pipelines/service.go
pkg/pipelines/service_test.go
pkg/pipelines/tekton_builder.go
pkg/pipelines/tekton_builder_test.go
pkg/pipelines/yaml/resources_test.go

/kind bug
Deployment of Argo CD apps failed because of the incorrect paths
Fixes https://github.com/redhat-developer/kam/issues/209
Test on Windows

KAM on windows uses backslash in paths (844)

---

pkg/pipelines/bootstrap.go
pkg/pipelines/bootstrap_test.go
pkg/pipelines/secrets/secrets.go

> /kind bug
Tekton expects a secret of type basic-auth to be present in the namespace which will be used for accessing private repositories. This PR adds the missing basic auth secret that was removed by #236 
Ref: https://github.com/tektoncd/pipeline/blob/main/docs/auth.md#understanding-credential-selection
Fixes https://issues.redhat.com/browse/GITOPS-1074
Day 1 and Day 2 operations with a private repository

Create basic auth secret for private repository

---

pkg/pipelines/service.go

> /kind bug
Sanitize the trigger binding name so it's a valid DNS1035 name
Fixes #?
1. Add an env and a service with long names
2. Create Webhook cmd should suceed

fix: sanitize trigger binding name

---

Dockerfile.serve

/kind cleanup
Update the base image from `rhscl/httpd-24-rhel7` to `rhel8-httpd-24`
Fixes #290 
1. Build an image for KAM with the updated image
2. KAM container should serve the kam binaries

Use rhel8/httpd-24 image to serve kam

---

Makefile

> /kind bug
it seems like kam pulls in the `net` package as a dependency which I suspect is causing `cgo` to be used for compilation indirectly and maybe causing kam to be dynamically linked. (This might also be putting the KAM binary in a position to benefit from supplying the `-buildmode=pie` flag) The [RPMDiff test](https://rpmdiff.engineering.redhat.com/run/527677/7/) in cpaas currently throws an error because we don't add the `-Wl,-z,now` flags for external linker while building the kam binary …

chore: add flags for external linker to satisfy RPMdiff bind-now test

---

test/e2e/kamsuite/kamsuite.go

> /kind bug
Changing the regexp slightly, to be able to create different GitOps repositories for OCP versions 4.10 and 4.11 in CI checks. 
Fixes #?

Create different GitOps repositories for different OCP versions in CI checks
